### ISSUE TITLE
FivetranOperatorAsync fails when using AWS SystemsManagerParameterStoreBackend secrets backend for fivetran_conn_id

### ISSUE THREAD

**Issue by stephanephanon** [astronomer/airflow-provider-fivetran-async#19]
**Apache Airflow version**
2.4.2

**Deployment** 
Astronomer Runtime 6.0.3 based on Airflow 2.4.2+astro.1

**Provider** 
airflow-provider-fivetran-async==1.0.0a5

**What happened**
- We have our fivetran connection in aws parameter store
- The FivetranOperatorAsync operator kicks off the sync in fivetran for our connector
- The task is deferred
- The connection to fivetran fails when the deferrable task is triggered to restart, with error "The conn_id `fivetran` isn't defined".
- The dag fails
- The fivetran sync continues to completion

NOTE: if we put the connection in the Airflow UI instead, then the deferrable task works as expected.

**What you think should happen instead**
The FivetranOperatorAsync should support aws parameter store as a secrets backend, or have a callout in the documentation that it only supports the two default secrets backends.

**How to reproduce**
- Configure airflow to use aws param store secrets backend
```
[secrets]
backend = airflow.providers.amazon.aws.secrets.systems_manager.SystemsManagerParameterStoreBackend
backend_kwargs = {"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables", "profile_name": "default"}
```
- Add a fivetran connection in aws param store called "/airflow/connections/fivetran"
- Create a dag that uses the FivetranOperatorAsync to trigger a fivetran connector sync using the fivetran connection in param store. 
```
fivetran_async = FivetranOperatorAsync(
	task_id="fivetran_async",
	connector_id="fivetran_connector",
	fivetran_conn_id="fivetran"
)
```
- Run the dag
- The sync will start. You can verify that it is running in fivetran.
- The dag will fail when the deferrable operator restarts

**Comment by phanikumv** [comment]
@pankajkoti can you please look into this during next week

**Comment by pankajkoti** [comment]
hi @stephanephanon I see in your Airflow [secrets] configuration, you have `profile: default` in the `backend_kwargs`.
In you Airflow worker, do you have a file `~/.aws/config` which contains the AWS access keys? If you have mounted such directory for your worker, could you also try mounting that file/directory on the triggerer?
