### ISSUE TITLE
Remove dependency on airflow-provider-fivetran

### ISSUE THREAD

**Issue by jlaneve** [astronomer/airflow-provider-fivetran-async#30]
Since https://github.com/fivetran/airflow-provider-fivetran is now deprecated, we should remove the dependency on it and instead move the code into this repo.

**Comment by pankajastro** [comment]
Hi @jlaneve do we want to maintain async operator only or sync too? I mean to run async user needs Airflow triggerer component too so I think it makes sense to maintain both WDYT?

**Comment by jlaneve** [comment]
Yeah we want to maintain both here
