### ISSUE TITLE
Merge sync and async operator sensor

### ISSUE THREAD

**Issue by pankajastro** [astronomer/airflow-provider-fivetran-async#35]
Merge sync and async operator sensor

depend on https://github.com/astronomer/airflow-provider-fivetran-async/pull/33

- [ ] Merge FivetranOperator and FivetranOperatorAsync, keep operator name FivetranOperator and add param `deferrable=True|False`
- [ ] Merge FivetranSensor and FivetranSensorAsync, keep sensor name FivetranSensor and add param `deferrable=True|False`
- [ ] Use pytest accross unit tests
- [ ] Deprecate existing FivetranSensorAsync and FivetranOperatorAsync

**Comment by pbhuss** [comment]
Please see https://github.com/astronomer/airflow-provider-fivetran-async/issues/45
