### ISSUE TITLE
fivetran_provider_async still has a reference to fivetran_provider

### ISSUE THREAD

**Issue by pbhuss** [astronomer/airflow-provider-fivetran-async#45]
This is caused by #33

`fivetran_provider_async` still has a reference to `fivetran_provider` on this line:
https://github.com/astronomer/airflow-provider-fivetran-async/blob/f89a9a04b7665c600ee44f615c1bb4b04f2b0f52/fivetran_provider_async/__init__.py#L31

This is causing import errors in the Airflow webserver logs:
```
[2023-08-10T14:39:57.174+0000] {providers_manager.py:253} WARNING - Exception when importing 'fivetran_provider.operators.fivetran.RegistryLink' from 'airflow-provider-fivetran-async' package

ModuleNotFoundError: No module named 'fivetran_provider'
```

**Comment by pankajkoti** [comment]
Thank you @pbhuss for the report. We just releases `1.1.2` of the provider. Could you please try the latest release https://pypi.org/project/airflow-provider-fivetran-async/
