### ISSUE TITLE
Fivetran Connection type not enabled in AWS MWAA with airflow version 2.6.3

### ISSUE THREAD

**Issue by Pavan1837** [astronomer/airflow-provider-fivetran-async#61]
HI,

I am trying to setup Fivetran connection type in AWS MWAA with **airflow version 2.6.3** . But i am not able see Fivetran as option in connection type drop down.

Steps:
I have installed **airflow-provider-fivetran-async==1.1.2** version and verified the installation successful.

Error:

DeprecationWarning: The provider airflow-provider-fivetran-async uses `hook-class-names` property in provider-info and has no `connection-types` one. The 'hook-class-names' property has been deprecated in favour of 'connection-types' in Airflow 2.2. Use **both** in case you want to have backwards compatibility with Airflow < 2.2..

Could you please suggest on this.

**Comment by Pavan1837** [comment]
@sunank200 @phanikumv Can you please look into this.

**Comment by pankajastro** [comment]
Have installed this package in your AWS MWAA env?

**Comment by Pavan1837** [comment]
Yes i have installed that package and the error message is being shown after successful installation

**Comment by pankajastro** [comment]
Aha, my bad!! you have already installed it.

**Comment by pankajastro** [comment]
removing the deprecated param makes sense but this is a warning, not an error (PR to remove it https://github.com/astronomer/airflow-provider-fivetran-async/pull/62) but I feel the connection type not visible has something to do with your installation. can try to test this PR once if this helps at least you will not get the above warning

**Comment by Pavan1837** [comment]
Could you please confirm if this package is tested in MWAA environment

**Comment by pankajastro** [comment]
> Could you please confirm if this package is tested in MWAA environment

I have not used MWAA! 
If this package works with Airflow and it does not work with MWAA then you should probably raise an issue with MWAA. A quick test can be done by 
- clone repo
- run command `make build-run` from the root folder 

The above command requires docker/docker-composer.

I did a quick test and I can see the options for the Fivetran connection.

**Comment by dwreeves** [comment]
@Pavan1837 -- MWAA pip installs both to the scheduler instance and the webserver instance.

If you are running MWAA with "WebserverAccessMode: PRIVATE_ONLY" mode, the webserver instance will not allow for outbound traffic, meaning that pip installs to PyPI won't work on the webserver, _even though_ it will work on the scheduler instance.

The way around this is to use a `plugins.zip` installation. You want to zip all wheels into a `plugins.zip` (`pip download -r requirements.txt -d wheels/` and then add this to the requirements.txt that you install to:

```
--find-links /usr/local/airflow/plugins
--no-index
```

A guide here about that: https://docs.aws.amazon.com/mwaa/latest/userguide/best-practices-dependencies.html

You can confirm that what I am saying is the issue by going to the Airflow UI, and in the top navigation bar go to `Admin -> Providers`. If you do _not_ see `airflow-provider-fivetran-async`, **and** you are running in `WebserverAccessMode: PRIVATE_ONLY` mode, **and** you also do not see _other_ Airflow provider packages that you have installed, then I would say this is the issue.

MWAA is very tedious 🙃 Acts as an advertisement for Astronomer's own managed service...

---

I would say that this issue should probably be closed as this is an MWAA deployment issue, not an issue specific to this package.

**Comment by phanikumv** [comment]
Thanks @dwreeves and @pankajastro . Closing this as per discussion above
