### ISSUE TITLE
Inconsistency in the Hooks Class

### ISSUE THREAD

**Issue by Nitindr** [astronomer/airflow-provider-fivetran-async#78]
We are using the new Async Operator for our Fivetran Sync in AWS MWAA 

`airflow-provider-fivetran-async==2.0.0`

and we are facing the below warning 

`
WARNING - Inconsistency! The hook class '<class 'fivetran_provider_async.hooks.FivetranHookAsync'>' declares connection type 'fivetran' but it is added by provider 'airflow-provider-fivetran-async' as connection_type 'Fivetran' in provider info. This should be fixed!
`
![image](https://github.com/astronomer/airflow-provider-fivetran-async/assets/117649501/87a5f4d5-3545-476c-ba75-dcea5bc1e317)

Is this anything we need to worry about or can it be ignored! please help me on this

**Comment by pankajastro** [comment]
hmm, I'm planning to release https://github.com/astronomer/airflow-provider-fivetran-async/pull/74 soon and it should fix this issue. thanks for reporting. 
I recommend you to test it once from the main branch if possible. just run `python3 -m build` from the root of this repo and it will generate a *.wh file for you. you can install this *.whl file and test it.

**Comment by pankajastro** [comment]
@Nitindr we have released 2.0.1. please do let me know if are still facing the issue

**Comment by pankajastro** [comment]
2.0.1  should fix it. closing this. feel free to re-open if issue still exist
