### ISSUE TITLE
FivetranOperatorAsync operator got stuck in Deferred mode (DAG job being deferred for 2 days)

### ISSUE THREAD

**Issue by shashankharsh** [astronomer/airflow-provider-fivetran-async#93]
Hi,
We are using fivetran_provider_async.operators.FivetranOperatorAsync operator to schedule Fivetran sync job. https://github.com/astronomer/airflow-provider-fivetran-async
Airflow DAG for Fivetran Connector ID: quoth_identities always get stuck in deferred status and can not complete the sync job.
I have raised a support ticket in GCP and ask GCP engineer to investigate Composer managed GKE cluster but they are not able to find any issue in the GKE cluster and mentioned as we're using a 3rd party tool with gcp so the issue is somethings from the Fivetran side.
Airflow version : 2.6.3
Composer version : 2.5.4
GKE version : 1.27.12-gke.1115000
airflow-provider-fivetran-async package version : 1.1.2
[raw_workday.candidate_interviews_airflow_dag_202504_deferred.txt](https://github.com/astronomer/airflow-provider-fivetran-async/files/15451066/raw_workday.candidate_interviews_airflow_dag_202504_deferred.txt)
[raw_workday.candidate_interviews_airflow_dag_20240504_success.txt](https://github.com/astronomer/airflow-provider-fivetran-async/files/15451067/raw_workday.candidate_interviews_airflow_dag_20240504_success.txt)
[user_login_info_prod_airflow_dag_20240505_failed.txt](https://github.com/astronomer/airflow-provider-fivetran-async/files/15451068/user_login_info_prod_airflow_dag_20240505_failed.txt)
[user_login_info_prod_airflow_dag_20240506_success.txt](https://github.com/astronomer/airflow-provider-fivetran-async/files/15451069/user_login_info_prod_airflow_dag_20240506_success.txt)

After that we had a call with Fivetran team and below are the summary:
1)  dp_candidate_interviews DAG job being deferred.
2) The Fivetran sync is being called through job every two hours, but being differed by 2 days. Sync is being deferred by 2 days as a result. There are occasional success.
3) Connector linked to this DAG is dp_candidate_interviews
4) You shared the Airflow logs and we could see connection not being established via API call to Fivetran API to trigger Fivetran sync via FivetranOperatorAsync. (**I shared the same logs here**)
We had raise case in the Fivetran support team (#201184).

**Comment by pankajastro** [comment]
Can you please upgrade `airflow-provider-fivetran-async` and verify if the issue still exists?

**Comment by pankajastro** [comment]
You’ve shared two logs for candidate_interviews_airflow_dag, one showing success and the other showing it deferred. Do you know if your environment was the same in both cases, or if there were any changes, such as connections, configurations or anything else?

**Comment by shashankharsh** [comment]
> Can you please upgrade `airflow-provider-fivetran-async` and verify if the issue still exists?

Hi, let me upgrade and verify this issue if still persist.

**Comment by shashankharsh** [comment]
> You’ve shared two logs for candidate_interviews_airflow_dag, one showing success and the other showing it deferred. Do you know if your environment was the same in both cases, or if there were any changes, such as connections, configurations or anything else?

yes, our environment is using same connections and configuration.

**Comment by pankajastro** [comment]
Hey @shashankharsh Just to confirm, does it always get stuck in the deferred state or only occasionally? Also, can you please share DAG to reproduce it?

**Comment by shashankharsh** [comment]
Hey @pankajastro , this issue is not reproducible after migrating the composer. I am closing this.
